# Generated by Django 4.0.1 on 2022-01-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notetitle', models.CharField(max_length=100)),
                ('notetext', models.CharField(max_length=200)),
            ],
        ),
    ]
